name: flash_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  animated_text_kit: ^4.2.2

  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  charts_flutter:
    git:
      url: https://github.com/google/charts
      path: charts_flutter

flutter:
  uses-material-design: true

  assets:
  - images/
