// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7DMWBmsP2Z_V94zfg2UAIjhdfp7-NxM8',
    appId: '1:183558736018:web:8c2a016f70e44885ef7e4b',
    messagingSenderId: '183558736018',
    projectId: 'flash-chat-b0f23',
    authDomain: 'flash-chat-b0f23.firebaseapp.com',
    storageBucket: 'flash-chat-b0f23.appspot.com',
    measurementId: 'G-YVMD3360J5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8wy5Nmr2gYtR-DMZeh5r-m4Gh0Nbsdz4',
    appId: '1:183558736018:android:687d4edd248f3e62ef7e4b',
    messagingSenderId: '183558736018',
    projectId: 'flash-chat-b0f23',
    storageBucket: 'flash-chat-b0f23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZPGn4z-qQRHsvUMI4JZJaHrTI5TpWuQQ',
    appId: '1:183558736018:ios:fa9be499da930affef7e4b',
    messagingSenderId: '183558736018',
    projectId: 'flash-chat-b0f23',
    storageBucket: 'flash-chat-b0f23.appspot.com',
    iosBundleId: 'com.rubenations.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZPGn4z-qQRHsvUMI4JZJaHrTI5TpWuQQ',
    appId: '1:183558736018:ios:6fe25347ff0c06f4ef7e4b',
    messagingSenderId: '183558736018',
    projectId: 'flash-chat-b0f23',
    storageBucket: 'flash-chat-b0f23.appspot.com',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7DMWBmsP2Z_V94zfg2UAIjhdfp7-NxM8',
    appId: '1:183558736018:web:45ab88d43e8a031def7e4b',
    messagingSenderId: '183558736018',
    projectId: 'flash-chat-b0f23',
    authDomain: 'flash-chat-b0f23.firebaseapp.com',
    storageBucket: 'flash-chat-b0f23.appspot.com',
    measurementId: 'G-ZB98003CRX',
  );
}
